//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ZensarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [Required(ErrorMessage ="Your Data is invalid")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string FName { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string LName { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string State { get; set; }
        [Required(ErrorMessage = "Your Data is invalid")]
        public string Gender { get; set; }
    }
}
